spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/expense_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  application:
    name: expense-tracker-bot

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}