package me.kmozze.expensetracker.adapter.ui

object Buttons {
    const val ADD_EXPENSE = "${Icons.PLUS} Добавить расход"
    const val VIEW_EXPENSES = "${Icons.LIST} Расходы"
    const val CATEGORIES = "${Icons.CATEGORY} Категории"
    const val STATISTICS = "${Icons.STATS} Статистика"
    const val TODAY = "${Icons.CALENDAR} Сегодня"
    const val YESTERDAY = "${Icons.CALENDAR} Вчера"
    const val ENTER_DATE_MANUALLY = "${Icons.EDIT} Ввести дату вручную"
    const val CANCEL = "${Icons.CANCEL} Отмена"
    const val FINISH_EXPENSE_EDIT = "${Icons.SUCCESS} Готово"
    const val EDIT_EXPENSE = "${Icons.EDIT} Изменить"
    const val DELETE_EXPENSE = "${Icons.DELETE} Удалить"
    const val CONFIRM_DELETE_EXPENSE = "${Icons.DELETE} Да, удалить"
    const val CANCEL_DELETE_EXPENSE = "${Icons.CANCEL} Нет"
    const val EDIT_EXPENSE_AMOUNT = "${Icons.EDIT} Сумма"
    const val EDIT_EXPENSE_CATEGORY = "${Icons.CATEGORY} Категория"
    const val EDIT_EXPENSE_DATE = "${Icons.CALENDAR} Дата"
    const val EDIT_EXPENSE_DESCRIPTION = "${Icons.EDIT} Описание"
    const val CHANGE_EXPENSE_LIST_PERIOD = "Изменить период 🗓"
    const val CHANGE_EXPENSE_LIST_CATEGORY = "Изменить категорию 📁"
    const val SHOW_EXPENSE_LIST = "🔎 Показать список"
    const val EXPENSE_LIST_PERIOD_DAY = "${Icons.CALENDAR} День"
    const val EXPENSE_LIST_PERIOD_WEEK = "${Icons.CALENDAR} Неделя"
    const val EXPENSE_LIST_PERIOD_MONTH = "${Icons.CALENDAR} Месяц"
    const val EXPENSE_LIST_PERIOD_ALL_TIME = "${Icons.CALENDAR} Все время"
    const val EXPENSE_LIST_CATEGORY_ALL = "Все"
    const val EXPENSE_LIST_PREVIOUS = "⬅️ Предыдущие"
    const val EXPENSE_LIST_NEXT = "Следующие ➡️"
}
